server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Customer
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, /orderStatuses/**
        - id: SMSExternal
          uri: http://localhost:8082
          predicates:
            - Path= 
        - id: PaymentExternal
          uri: http://localhost:8083
          predicates:
            - Path= 
        - id: Delivery
          uri: http://localhost:8084
          predicates:
            - Path=/deliveries/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Customer
          uri: http://Customer:8080
          predicates:
            - Path=/orders/**, /orderStatuses/**
        - id: SMSExternal
          uri: http://SMSExternal:8080
          predicates:
            - Path= 
        - id: PaymentExternal
          uri: http://PaymentExternal:8080
          predicates:
            - Path= 
        - id: Delivery
          uri: http://Delivery:8080
          predicates:
            - Path=/deliveries/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
